"""
Django settings for unkata project.

Generated by 'django-admin startproject' using Django 1.11.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/

export DJANGO_SETTINGS_MODULE=gsone.settings_test
"""

from .settings import *

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# Environment
ENV = 'testing'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DATABASE_NAME', 'test'),
        'USER': os.environ.get('DATABASE_USER', 'test'),
        'PASSWORD': os.environ.get('DATABASE_PASSWORD', 'test'),
        'HOST': os.environ.get('DATABASE_HOST', '127.0.0.1'),
        'PORT':  os.environ.get('DATABASE_PORT', '5432'),
    }
}

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.locmem.EmailBackend'
EMAIL_FROM = 'info@localhost'

# Celery settings
CELERY_TASK_ALWAYS_EAGER = True

CELERY_EAGER_PROPAGATES_EXCEPTIONS = True
